-- جداول (لا enum)
create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  location text,
  type text,
  description text,
  requirements text,
  status text default 'open',
  created_at timestamptz default now()
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  job_id bigint references public.jobs(id) on delete cascade,
  full_name text not null,
  email text,
  phone text,
  summary text,
  cv_url text,
  status text default 'new',
  ai_score int,
  ai_notes text,
  created_at timestamptz default now()
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  role text check (role in ('admin','recruiter','manager','viewer')) default 'viewer',
  created_at timestamptz default now()
);

-- Bucket CV
select storage.create_bucket('cv', public => true);

-- تفعيل RLS
alter table public.jobs enable row level security;
alter table public.applications enable row level security;
alter table public.profiles enable row level security;

-- مساعد: هل المستخدم له دور ضمن مجموعة معينة؟
create or replace function public.has_role(roles text[])
returns boolean language sql stable as $$
  select exists(
    select 1 from public.profiles p
    where p.user_id = auth.uid() and p.role = any(roles)
  );
$$;

-- سياسات jobs
drop policy if exists "jobs public read" on public.jobs;
create policy "jobs public read" on public.jobs
for select to public using (true);

drop policy if exists "jobs write by staff" on public.jobs;
create policy "jobs write by staff" on public.jobs
for all to authenticated
using (public.has_role(array['admin','recruiter','manager']))
with check (public.has_role(array['admin','recruiter','manager']));

-- سياسات applications
drop policy if exists "applications public insert" on public.applications;
create policy "applications public insert" on public.applications
for insert to public with check (true);

drop policy if exists "applications staff read" on public.applications;
create policy "applications staff read" on public.applications
for select to authenticated
using (public.has_role(array['admin','recruiter','manager']));

drop policy if exists "applications staff update" on public.applications;
create policy "applications staff update" on public.applications
for update to authenticated
using (public.has_role(array['admin','recruiter','manager']))
with check (public.has_role(array['admin','recruiter','manager']));

-- سياسات profiles
drop policy if exists "profiles self read" on public.profiles;
create policy "profiles self read" on public.profiles
for select to authenticated
using (user_id = auth.uid());

drop policy if exists "profiles admin read all" on public.profiles;
create policy "profiles admin read all" on public.profiles
for select to authenticated
using (public.has_role(array['admin']));

drop policy if exists "profiles self upsert" on public.profiles;
create policy "profiles self upsert" on public.profiles
for insert to authenticated with check (user_id = auth.uid());
create policy "profiles self update" on public.profiles
for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "profiles admin write all" on public.profiles;
create policy "profiles admin write all" on public.profiles
for all to authenticated
using (public.has_role(array['admin']))
with check (public.has_role(array['admin']));

-- سياسات تخزين للـ cv bucket
drop policy if exists "cv public read" on storage.objects;
create policy "cv public read"
on storage.objects for select to public using (bucket_id = 'cv');

drop policy if exists "cv public upload" on storage.objects;
create policy "cv public upload"
on storage.objects for insert to public with check (bucket_id = 'cv');

drop policy if exists "cv staff remove" on storage.objects;
create policy "cv staff remove"
on storage.objects for delete to authenticated using (bucket_id = 'cv' and public.has_role(array['admin','recruiter','manager']));

-- RPC: ترقية/تعيين دور مستخدم عبر البريد (security definer)
create or replace function public.promote_user_by_email(p_email text, p_role text)
returns boolean
language plpgsql
security definer
as $$
declare
  v_uid uuid;
  v_is_admin boolean;
begin
  if p_role not in ('admin','recruiter','manager','viewer') then
    raise exception 'invalid role';
  end if;

  -- تحقق أن المنفذ Admin (ما عدا الحالة الخاصة الأولى)
  select public.has_role(array['admin']) into v_is_admin;
  if not v_is_admin then
    -- اسمح فقط لو لم توجد أي صفوف بعد (تهيئة أولى)
    if exists (select 1 from public.profiles) then
      raise exception 'only admin can promote';
    end if;
  end if;

  select id into v_uid from auth.users where email = p_email;
  if v_uid is null then
    raise exception 'user not found in auth.users; user must sign up/login first';
  end if;

  insert into public.profiles(user_id,email,role)
  values (v_uid,p_email,p_role)
  on conflict (user_id) do update set email=excluded.email, role=excluded.role;

  return true;
end;
$$;
